home:
 path: /
 defaults: { _controller: AppBundle:Home:home }

showUserPost:
 path: /showUserPost
 defaults: { _controller: AppBundle:Post:showUserPost }

deletePost:
 path: /deletePost/{post_id}
 defaults: { _controller: AppBundle:Post:deletePost }

like:
 path: /like/{post_id}
 defaults: { _controller: AppBundle:Post:like }

unlike:
 path: /unlike/{post_id}
 defaults: { _controller: AppBundle:Post:unlike }

register:
 path: /register
 defaults: { _controller: AppBundle:User:register}

createUserOk:
 path: /createUserOk
 defaults: { _controller: AppBundle:User:validation}

login:
 path: /login
 defaults: { _controller: AppBundle:User:login}

logout:
 path: /logout