home:
 path: /home
 defaults: { _controller: AppBundle:Home:home }

sign_in:
 path: /sign_in
 defaults: { _controller: AppBundle:Login:connexion}

login:
 path: /login
 defaults: { _controller: AppBundle:Login:login}

logout:
 path: /logout