# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        dbprovider:
            entity:
                class: AppBundle:User
                property: username
        #webservice:
         #   id: AppBundle\Security\User\WebserviceUserProvider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: dbprovider
            form_login:
                    login_path: login
                    check_path: login
            logout:
                path: /logout
                target: /
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }


